FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
#RUN echo "fs.inotify.max_user_instances=524288" >> /etc/sysctl.conf && sysctl -p
#RUN echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf
#RUN echo "fs.inotify.max_queued_events=524288" >> /etc/sysctl.conf

COPY . . 

CMD ["npm", "run", "start"] 
